spring:
  profiles: ha-provider1
  application:
    name: ha-provider
  cloud:
    inetutils: ## 网卡设置
      ignoredInterfaces:  ## 忽略的网卡
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:  ## 优先的网段
        - 172.20
server:
  port: 40001
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:30001/eureka,http://localhost:30002/eureka


---
spring:
  profiles: ha-provider2
  application:
    name: ha-provider
  cloud:
    inetutils: ## 网卡设置
      ignoredInterfaces:  ## 忽略的网卡
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:  ## 优先的网段
        - 172.20
server:
  port: 40002
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:30001/eureka,http://localhost:30002/eureka
