spring:
  profiles: eureka-center1
server:
  port: 30001
eureka:
  instance:
    hostname: ha-eureak-center1
    appname: 注册中心
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:30002/eureka


---
spring:
  profiles: eureka-center2
server:
  port: 30002
eureka:
  instance:
    hostname: ha-eureak-center2
    appname: 注册中心
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:30001/eureka



